<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="05068-020L" name="testCases.TC_TerritorryManagerTasks" tests="7" failures="1" timestamp="23 Jan 2019 12:32:10 GMT" time="7.289" errors="0">
  <testcase name="TC001_Verify_Navigate_TO_Territorry_Manager_Task" time="6.974" classname="testCases.TC_TerritorryManagerTasks"/>
  <testcase name="TC_004_verify_Start_From_Date_Text" time="0.051" classname="testCases.TC_TerritorryManagerTasks"/>
  <testcase name="TC_007_verify_Status_Text" time="0.047" classname="testCases.TC_TerritorryManagerTasks"/>
  <testcase name="TC_006_verify_Territory_Text" time="0.059" classname="testCases.TC_TerritorryManagerTasks"/>
  <testcase name="TC_002_verify_User" time="0.047" classname="testCases.TC_TerritorryManagerTasks">
    <failure type="java.lang.AssertionError" message="expected [supun_zincat] but found [Supun_zincat]">
      <![CDATA[java.lang.AssertionError: expected [supun_zincat] but found [Supun_zincat]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at pages.TerritorryManagerTasks.VerifyText(TerritorryManagerTasks.java:55)
	at pages.TerritorryManagerTasks.VeriUsername(TerritorryManagerTasks.java:61)
	at testCases.TC_TerritorryManagerTasks.TC_002_verify_User(TC_TerritorryManagerTasks.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_002_verify_User -->
  <testcase name="TC_003_verify_header_text" time="0.073" classname="testCases.TC_TerritorryManagerTasks"/>
  <testcase name="TC_005_verify_End_Date_text" time="0.038" classname="testCases.TC_TerritorryManagerTasks"/>
</testsuite> <!-- testCases.TC_TerritorryManagerTasks -->
