<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="05068-020L" name="testCases.TS_001_Sales_Planning" tests="24" failures="3" timestamp="14 Mar 2019 11:22:46 GMT" time="19.575" errors="1">
  <testcase name="TC_016_Verify_select_GN_Division" time="1.970" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_010_VerifyIs_District_DropdownEnabled" time="0.053" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_0181_verify_select_EndDate" time="0.403" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_004_Verify_TerriTory_Lable" time="0.049" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_006_Verify_StartDate_Lable" time="0.063" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_003_Verify_District_Lable" time="0.803" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_014_districtValue" time="0.000" classname="testCases.TS_001_Sales_Planning">
    <error type="java.lang.Error" message="Unresolved compilation problem: 
	Syntax error on token &quot;for&quot;, delete this token
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
	Syntax error on token "for", delete this token

	at pages.SalesPlanningPage.verifyDistrictDropdownValues(SalesPlanningPage.java:164)
	at testCases.TS_001_Sales_Planning.TC_014_districtValue(TS_001_Sales_Planning.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC_014_districtValue -->
  <testcase name="TC_019_verify_Click_tower_Check_Box" time="1.042" classname="testCases.TS_001_Sales_Planning">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at proxy.verifications.ClickonCheckBox(verifications.java:96)
	at pages.SalesPlanningPage.ClickonToweCheckBox(SalesPlanningPage.java:252)
	at testCases.TS_001_Sales_Planning.TC_019_verify_Click_tower_Check_Box(TS_001_Sales_Planning.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_019_verify_Click_tower_Check_Box -->
  <testcase name="TC_021_verify_Cancle_Submission" time="0.416" classname="testCases.TS_001_Sales_Planning">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at pages.SalesPlanningPage.ClickOnCancleButton(SalesPlanningPage.java:288)
	at testCases.TS_001_Sales_Planning.TC_021_verify_Cancle_Submission(TS_001_Sales_Planning.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_021_verify_Cancle_Submission -->
  <testcase name="TC_011_VerifyIs_Territory_DropdownEnabled" time="0.047" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_008_Verify_Tower_Lable" time="0.046" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="close" time="0.000" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_009_Verify_Remarks_Lable" time="0.047" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_007_Verify_EndDate_Lable" time="0.047" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_015_select_Terriotorry" time="0.873" classname="testCases.TS_001_Sales_Planning">
    <failure type="java.lang.AssertionError" message="expected [COL - Colombo Depot] but found [COL - Colombo Depot
 ]">
      <![CDATA[java.lang.AssertionError: expected [COL - Colombo Depot] but found [COL - Colombo Depot
 ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at proxy.verifications.verifyGlobalSelectDropDown(verifications.java:68)
	at pages.SalesPlanningPage.verifySelectedTerriotarry(SalesPlanningPage.java:178)
	at testCases.TS_001_Sales_Planning.TC_015_select_Terriotorry(TS_001_Sales_Planning.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_015_select_Terriotorry -->
  <testcase name="TC_014_select_districtValue" time="1.058" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_013_VerifyIs_Towers_DropdownEnabled" time="0.071" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_022_verify_SubmitSuccessFully" time="0.002" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_002_Verify_navigateTo_SalesPlanning" time="5.564" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_001_verify_User_Able_TO_Navigate_Dashboard" time="5.671" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_020_verify_Confirm_message" time="0.717" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_005_Verify_GnDivision_Lable" time="0.055" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_012_VerifyIs_GNDivisions_DropdownEnabled" time="0.063" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_017_verify_select_StarttDate" time="0.515" classname="testCases.TS_001_Sales_Planning"/>
</testsuite> <!-- testCases.TS_001_Sales_Planning -->
