<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="05068-020L" name="testCases.TS_002_AssignedTasks" tests="17" failures="3" timestamp="28 Mar 2019 12:52:03 GMT" time="23.514" errors="0">
  <testcase name="TC_010_Verify_select_District" time="0.898" classname="testCases.TS_002_AssignedTasks">
    <failure type="java.lang.AssertionError" message="expected [Colombo] but found [Colombo
 ]">
      <![CDATA[java.lang.AssertionError: expected [Colombo] but found [Colombo
 ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at proxy.verifications.verifyGlobalSelectDropDown(verifications.java:122)
	at pages.AssignedTaskedPage.verifySelectDistrict(AssignedTaskedPage.java:147)
	at testCases.TS_002_AssignedTasks.TC_010_Verify_select_District(TS_002_AssignedTasks.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_010_Verify_select_District -->
  <testcase name="TC_012_Verify_select_Status" time="0.262" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_007_verify_Status_Lable" time="0.038" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_005_verify_District_Lable" time="0.044" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_001_Verify_navigate_To_wom" time="5.540" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_008_Verify_select_StartDate" time="0.449" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_016Verify_Grid_View" time="0.117" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_014_Verify_Multiselect_Functionlity_OF_District_Dropdown" time="0.496" classname="testCases.TS_002_AssignedTasks">
    <failure type="java.lang.AssertionError" message="expected [2 Items Selected] but found [2 Items Selected
 ]">
      <![CDATA[java.lang.AssertionError: expected [2 Items Selected] but found [2 Items Selected
 ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at pages.AssignedTaskedPage.VerifyMultiSelectFunctionality(AssignedTaskedPage.java:258)
	at pages.AssignedTaskedPage.multiselectrDistrict(AssignedTaskedPage.java:270)
	at testCases.TS_002_AssignedTasks.TC_014_Verify_Multiselect_Functionlity_OF_District_Dropdown(TS_002_AssignedTasks.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_014_Verify_Multiselect_Functionlity_OF_District_Dropdown -->
  <testcase name="TC_006_verify_Territory_Lable" time="0.056" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_009_Verify_select_endDate" time="0.399" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_004_verify_EndDate_Lable" time="0.033" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_003_verify_SartFrom_Lable" time="0.047" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_017_uit" time="0.001" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_011_vrify_select_Territorry" time="0.955" classname="testCases.TS_002_AssignedTasks">
    <failure type="java.lang.AssertionError" message="expected [COL - Colombo Depot] but found [COL - Colombo Depot
 ]">
      <![CDATA[java.lang.AssertionError: expected [COL - Colombo Depot] but found [COL - Colombo Depot
 ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at proxy.verifications.verifyGlobalSelectDropDown(verifications.java:122)
	at pages.AssignedTaskedPage.SelectTerritorry(AssignedTaskedPage.java:156)
	at testCases.TS_002_AssignedTasks.TC_011_vrify_select_Territorry(TS_002_AssignedTasks.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_011_vrify_select_Territorry -->
  <testcase name="TC_002_Verify_Navigate_TO_MyTask" time="6.071" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_015_Verify_Table_View" time="7.993" classname="testCases.TS_002_AssignedTasks"/>
  <testcase name="TC_013_Verify_click_sublit" time="0.115" classname="testCases.TS_002_AssignedTasks"/>
</testsuite> <!-- testCases.TS_002_AssignedTasks -->
