<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" total="25" passed="18">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="48243" started-at="2019-09-05T09:53:21Z" finished-at="2019-09-05T09:54:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="48243" started-at="2019-09-05T09:53:21Z" finished-at="2019-09-05T09:54:10Z">
      <class name="testCases.TS_001_Sales_Planning">
        <test-method status="PASS" signature="LoginTowom()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="LoginTowom" is-config="true" duration-ms="6266" started-at="2019-09-05T15:23:21Z" finished-at="2019-09-05T15:23:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTowom -->
        <test-method status="PASS" signature="TC_001_Verify_navigateTo_SalesPlanning()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_001_Verify_navigateTo_SalesPlanning" duration-ms="8450" started-at="2019-09-05T15:23:28Z" finished-at="2019-09-05T15:23:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001_Verify_navigateTo_SalesPlanning -->
        <test-method status="PASS" signature="TC_003_Verify_District_Lable()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_003_Verify_District_Lable" duration-ms="796" started-at="2019-09-05T15:23:36Z" finished-at="2019-09-05T15:23:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_003_Verify_District_Lable -->
        <test-method status="PASS" signature="TC_004_Verify_TerriTory_Lable()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_004_Verify_TerriTory_Lable" duration-ms="580" started-at="2019-09-05T15:23:37Z" finished-at="2019-09-05T15:23:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_004_Verify_TerriTory_Lable -->
        <test-method status="PASS" signature="TC_005_Verify_GnDivision_Lable()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_005_Verify_GnDivision_Lable" duration-ms="538" started-at="2019-09-05T15:23:38Z" finished-at="2019-09-05T15:23:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_005_Verify_GnDivision_Lable -->
        <test-method status="PASS" signature="TC_006_Verify_StartDate_Lable()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_006_Verify_StartDate_Lable" duration-ms="556" started-at="2019-09-05T15:23:38Z" finished-at="2019-09-05T15:23:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_006_Verify_StartDate_Lable -->
        <test-method status="PASS" signature="TC_007_Verify_EndDate_Lable()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_007_Verify_EndDate_Lable" duration-ms="561" started-at="2019-09-05T15:23:39Z" finished-at="2019-09-05T15:23:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_007_Verify_EndDate_Lable -->
        <test-method status="PASS" signature="TC_008_Verify_Tower_Lable()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_008_Verify_Tower_Lable" duration-ms="538" started-at="2019-09-05T15:23:39Z" finished-at="2019-09-05T15:23:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_008_Verify_Tower_Lable -->
        <test-method status="PASS" signature="TC_009_Verify_Remarks_Lable()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_009_Verify_Remarks_Lable" duration-ms="554" started-at="2019-09-05T15:23:40Z" finished-at="2019-09-05T15:23:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_009_Verify_Remarks_Lable -->
        <test-method status="PASS" signature="TC_010_VerifyIs_District_DropdownEnabled()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_010_VerifyIs_District_DropdownEnabled" duration-ms="37" started-at="2019-09-05T15:23:40Z" finished-at="2019-09-05T15:23:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_010_VerifyIs_District_DropdownEnabled -->
        <test-method status="PASS" signature="TC_011_VerifyIs_Territory_DropdownEnabled()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_011_VerifyIs_Territory_DropdownEnabled" duration-ms="34" started-at="2019-09-05T15:23:40Z" finished-at="2019-09-05T15:23:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_011_VerifyIs_Territory_DropdownEnabled -->
        <test-method status="PASS" signature="TC_012_VerifyIs_GNDivisions_DropdownEnabled()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_012_VerifyIs_GNDivisions_DropdownEnabled" duration-ms="32" started-at="2019-09-05T15:23:40Z" finished-at="2019-09-05T15:23:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_012_VerifyIs_GNDivisions_DropdownEnabled -->
        <test-method status="PASS" signature="TC_013_VerifyIs_Towers_DropdownEnabled()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_013_VerifyIs_Towers_DropdownEnabled" duration-ms="45" started-at="2019-09-05T15:23:40Z" finished-at="2019-09-05T15:23:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_013_VerifyIs_Towers_DropdownEnabled -->
        <test-method status="FAIL" signature="TC_0014_verifyDistrictvalues()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_0014_verifyDistrictvalues" duration-ms="460" started-at="2019-09-05T15:23:40Z" finished-at="2019-09-05T15:23:41Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[9]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 9
	at proxy.verifications.verifyAllDropdownValues(verifications.java:56)
	at pages.DashboardPage.verifyAllTheDistrictdropdownValues(DashboardPage.java:204)
	at testCases.TS_001_Sales_Planning.TC_0014_verifyDistrictvalues(TS_001_Sales_Planning.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0014_verifyDistrictvalues -->
        <test-method status="PASS" signature="TC_015_select_districtValue()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_015_select_districtValue" duration-ms="1159" started-at="2019-09-05T15:23:41Z" finished-at="2019-09-05T15:23:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_015_select_districtValue -->
        <test-method status="FAIL" signature="TC_016_verifyTerritoryvalues()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_016_verifyTerritoryvalues" duration-ms="664" started-at="2019-09-05T15:23:42Z" finished-at="2019-09-05T15:23:43Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 4
	at proxy.verifications.verifyAllDropdownValues(verifications.java:56)
	at pages.DashboardPage.verifyAllTheTerritorrdropdownValues(DashboardPage.java:212)
	at testCases.TS_001_Sales_Planning.TC_016_verifyTerritoryvalues(TS_001_Sales_Planning.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_016_verifyTerritoryvalues -->
        <test-method status="FAIL" signature="TC_017_select_Terriotorry()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_017_select_Terriotorry" duration-ms="1106" started-at="2019-09-05T15:23:43Z" finished-at="2019-09-05T15:23:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [AWI - Awissawella Depot] but found [COL - Colombo Depot
 ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [AWI - Awissawella Depot] but found [COL - Colombo Depot
 ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at proxy.verifications.verifyGlobalSelectDropDown(verifications.java:124)
	at pages.SalesPlanningPage.verifySelectedTerriotarry(SalesPlanningPage.java:180)
	at testCases.TS_001_Sales_Planning.TC_017_select_Terriotorry(TS_001_Sales_Planning.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_017_select_Terriotorry -->
        <test-method status="PASS" signature="TC_018_Verify_select_GN_Division()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_018_Verify_select_GN_Division" duration-ms="2191" started-at="2019-09-05T15:23:44Z" finished-at="2019-09-05T15:23:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_018_Verify_select_GN_Division -->
        <test-method status="PASS" signature="TC_019_verify_select_StarttDate()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_019_verify_select_StarttDate" duration-ms="800" started-at="2019-09-05T15:23:46Z" finished-at="2019-09-05T15:23:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_019_verify_select_StarttDate -->
        <test-method status="PASS" signature="TC_020_verify_select_EndDate()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_020_verify_select_EndDate" duration-ms="452" started-at="2019-09-05T15:23:47Z" finished-at="2019-09-05T15:23:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_020_verify_select_EndDate -->
        <test-method status="FAIL" signature="TC_021_verify_Click_tower_Check_Box()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_021_verify_Click_tower_Check_Box" duration-ms="1938" started-at="2019-09-05T15:23:47Z" finished-at="2019-09-05T15:23:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at proxy.verifications.ClickonCheckBox(verifications.java:172)
	at pages.SalesPlanningPage.ClickonToweCheckBox(SalesPlanningPage.java:254)
	at testCases.TS_001_Sales_Planning.TC_021_verify_Click_tower_Check_Box(TS_001_Sales_Planning.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_021_verify_Click_tower_Check_Box -->
        <test-method status="PASS" signature="TC_022_verify_Confirm_message()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_022_verify_Confirm_message" duration-ms="1540" started-at="2019-09-05T15:23:49Z" finished-at="2019-09-05T15:23:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_022_verify_Confirm_message -->
        <test-method status="FAIL" signature="TC_023_verify_Cancle_Submission()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_023_verify_Cancle_Submission" duration-ms="388" started-at="2019-09-05T15:23:51Z" finished-at="2019-09-05T15:23:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at pages.SalesPlanningPage.ClickOnCancleButton(SalesPlanningPage.java:290)
	at testCases.TS_001_Sales_Planning.TC_023_verify_Cancle_Submission(TS_001_Sales_Planning.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_023_verify_Cancle_Submission -->
        <test-method status="FAIL" signature="TC_024_verify_SubmitSuccessFully()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_024_verify_SubmitSuccessFully" duration-ms="17901" started-at="2019-09-05T15:23:51Z" finished-at="2019-09-05T15:24:09Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy8.getText(Unknown Source)
	at pages.SalesPlanningPage.MessageBoxcSubmitbutton(SalesPlanningPage.java:310)
	at testCases.TS_001_Sales_Planning.TC_024_verify_SubmitSuccessFully(TS_001_Sales_Planning.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_024_verify_SubmitSuccessFully -->
        <test-method status="FAIL" signature="TC_025_districtValue()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="TC_025_districtValue" duration-ms="552" started-at="2019-09-05T15:24:09Z" finished-at="2019-09-05T15:24:10Z">
          <exception class="org.openqa.selenium.NoSuchWindowException">
            <message>
              <![CDATA[no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=76.0.3809.132)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:05:20.749Z'
System info: host: '05068-020L', ip: '172.22.101.88', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.42.591088 (7b2b2dca23cca0..., userDataDir: C:\Users\SUPUN_~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:53818}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 76.0.3809.132, webStorageEnabled: true}
Session ID: e4be8992d5c462d026af36d27bbf40c8
*** Element info: {Using=xpath, value=//*[@id='districts_filter_rightbar']}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=76.0.3809.132)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:05:20.749Z'
System info: host: '05068-020L', ip: '172.22.101.88', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.42.591088 (7b2b2dca23cca0..., userDataDir: C:\Users\SUPUN_~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:53818}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 76.0.3809.132, webStorageEnabled: true}
Session ID: e4be8992d5c462d026af36d27bbf40c8
*** Element info: {Using=xpath, value=//*[@id='districts_filter_rightbar']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:424)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy8.getTagName(Unknown Source)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:44)
	at pages.SalesPlanningPage.verifyDistrictDropdownValues(SalesPlanningPage.java:163)
	at testCases.TS_001_Sales_Planning.TC_025_districtValue(TS_001_Sales_Planning.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchWindowException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_025_districtValue -->
        <test-method status="PASS" signature="close()[pri:0, instance:testCases.TS_001_Sales_Planning@6392827e]" name="close" duration-ms="1" started-at="2019-09-05T15:24:10Z" finished-at="2019-09-05T15:24:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- testCases.TS_001_Sales_Planning -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
